
services:

  backend:
    build: ./backend
    image: eu.gcr.io/thehomedisplay/backend
    ports:
      - "3000:3000"
    environment:
      DB_HOST: /cloudsql/thehomedisplay:europe-west9:thehomedisplayorigin
      DB_USER: myroot
      DB_PASSWORD: mypassword
      DB_NAME: thehomedisplay
      JWT_SECRET: mySuperSecretKey
      DEFAULT_ADMIN_NAME: admin
      DEFAULT_ADMIN_PASSWORD: password
    networks:
      - backend-network

networks:
  backend-network:
    driver: bridge
