CREATE DATABASE IF NOT EXISTS `thehomedisplay`;
USE thehomedisplay;

DROP TABLE IF EXISTS users;
CREATE TABLE IF NOT EXISTS user (
  id INT AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(255) NOT NULL UNIQUE,
  email VARCHAR(255) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL
);

DROP TABLE IF EXISTS notes;
CREATE TABLE IF NOT EXISTS notes (
    id INT PRIMARY KEY,
    note TEXT NOT NULL
);

